# Generated by Django 5.0.2 on 2024-02-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=800)),
                ('likes', models.IntegerField(max_length=100)),
                ('comments', models.IntegerField(max_length=100)),
                ('shares', models.IntegerField(max_length=100)),
                ('reactions_count', models.IntegerField(max_length=100)),
            ],
        ),
    ]
