# Generated by Django 5.0.2 on 2024-02-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_api', '0002_datos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='comments',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='datos',
            name='likes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='datos',
            name='reactions_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='datos',
            name='shares',
            field=models.IntegerField(),
        ),
    ]
