# Generated by Django 5.0.2 on 2024-02-18 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_api', '0003_alter_datos_comments_alter_datos_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos',
            name='emociones',
            field=models.CharField(default='', max_length=800),
        ),
    ]
