# Generated by Django 5.0.2 on 2024-02-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_api', '0004_datos_emociones'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos',
            name='sentimientos',
            field=models.CharField(default='', max_length=800),
        ),
    ]
